{
    "checksum": "e6682c9cda4a069f82853fbc0dfb264cd39192fc3fd17b47c6839f4594e0274b",
    "file": "api.rst",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/plain"
    },
    "number_of_duplicates": 1,
    "package": "python-os-faults",
    "path": "python-os-faults/0.2.1-3/doc/source/api.rst",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-os-faults/0.2.1-3/",
        "metric": {
            "size": 668
        },
        "pts_link": "https://tracker.debian.org/pkg/python-os-faults",
        "sloc": [
            [
                "python",
                4680
            ],
            [
                "sh",
                54
            ],
            [
                "makefile",
                24
            ]
        ],
        "suites": [
            "bookworm",
            "bullseye",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/openstack-team/libs/python-os-faults",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-os-faults/0.2.1-3/doc/source/api.rst",
    "stat": {
        "perms": "rw-r--r--",
        "size": 359,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "0.2.1-3"
}