{
    "checksum": "b78c80e90112bd4a93c24cb09c35edb12035745d047d6116f10722ef2ce5162c",
    "file": "snmp-data-constraints-verification-failure.rst",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/plain"
    },
    "number_of_duplicates": 4,
    "package": "python-pysnmp4",
    "path": "python-pysnmp4/4.4.12-2/docs/source/faq/snmp-data-constraints-verification-failure.rst",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-pysnmp4/4.4.12-2/",
        "metric": {
            "size": 3476
        },
        "pts_link": "https://tracker.debian.org/pkg/python-pysnmp4",
        "sloc": [
            [
                "python",
                20332
            ],
            [
                "makefile",
                166
            ],
            [
                "sh",
                23
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/packages/python-pysnmp4",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-pysnmp4/4.4.12-2/docs/source/faq/snmp-data-constraints-verification-failure.rst",
    "stat": {
        "perms": "rw-r--r--",
        "size": 1596,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "4.4.12-2"
}