{
    "checksum": "0be0b3958d812611b0a0954d57b14d7a3d896ab6c57befe0fdd9af5c2d190e42",
    "file": "vendordata-reboot-hard-failure-42beeb1044680a50.yaml",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/plain"
    },
    "number_of_duplicates": 3,
    "package": "nova",
    "path": "nova/2:24.0.0-1/releasenotes/notes/vendordata-reboot-hard-failure-42beeb1044680a50.yaml",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/nova/2:24.0.0-1/",
        "metric": {
            "size": 47244
        },
        "pts_link": "https://tracker.debian.org/pkg/nova",
        "sloc": [
            [
                "python",
                384417
            ],
            [
                "pascal",
                1791
            ],
            [
                "sh",
                892
            ],
            [
                "makefile",
                149
            ],
            [
                "xml",
                83
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/openstack-team/services/nova",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/n/nova/2%3A24.0.0-1/releasenotes/notes/vendordata-reboot-hard-failure-42beeb1044680a50.yaml",
    "stat": {
        "perms": "rw-r--r--",
        "size": 289,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "2:24.0.0-1"
}