{
    "checksum": "5c05fcb52afbac68008efe9342a93b6fe48543ba7bd87efe68b9a2e75f603138",
    "file": "29_fix_urandom_error.dpatch",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-shellscript"
    },
    "number_of_duplicates": 4,
    "package": "bittornado",
    "path": "bittornado/0.3.18-10.3/debian/patches/29_fix_urandom_error.dpatch",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 3675,
        "license": "/copyright/license/bittornado/0.3.18-10.3/",
        "metric": {
            "size": 3624
        },
        "pts_link": "https://tracker.debian.org/pkg/bittornado",
        "sloc": [
            [
                "python",
                16627
            ],
            [
                "sh",
                4400
            ],
            [
                "makefile",
                54
            ]
        ],
        "suites": [
            "buster"
        ],
        "vcs_browser": "http://svn.debian.org/wsvn/pkg-bittornado/bittornado/trunk/",
        "vcs_type": "svn"
    },
    "raw_url": "/data/main/b/bittornado/0.3.18-10.3/debian/patches/29_fix_urandom_error.dpatch",
    "stat": {
        "perms": "rw-r--r--",
        "size": 620,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "0.3.18-10.3"
}