{
    "checksum": "e2869424601419d991b94af0b0ce035b1993d5885f0c27a2ea51f08350aa0165",
    "file": "exceptions_2_5.py",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-python"
    },
    "number_of_duplicates": 3,
    "package": "python-proboscis",
    "path": "python-proboscis/1.2.6.0-5/proboscis/compatability/exceptions_2_5.py",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-proboscis/1.2.6.0-5/",
        "metric": {
            "size": 180
        },
        "pts_link": "https://tracker.debian.org/pkg/python-proboscis",
        "sloc": [
            [
                "python",
                1103
            ],
            [
                "makefile",
                13
            ]
        ],
        "suites": [
            "bookworm",
            "bullseye",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/openstack-team/python/python-proboscis",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-proboscis/1.2.6.0-5/proboscis/compatability/exceptions_2_5.py",
    "stat": {
        "perms": "rw-r--r--",
        "size": 1186,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "1.2.6.0-5"
}