{
    "checksum": "b14899a3cf59ef1f75250110c7ee91f79dd7cca1930cd0e826c6a45a05a34403",
    "file": "cmd.py",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-python"
    },
    "number_of_duplicates": 1,
    "package": "python-os-faults",
    "path": "python-os-faults/0.2.1-3/os_faults/cmd/cmd.py",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-os-faults/0.2.1-3/",
        "metric": {
            "size": 668
        },
        "pts_link": "https://tracker.debian.org/pkg/python-os-faults",
        "sloc": [
            [
                "python",
                4680
            ],
            [
                "sh",
                54
            ],
            [
                "makefile",
                24
            ]
        ],
        "suites": [
            "bookworm",
            "bullseye",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/openstack-team/libs/python-os-faults",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-os-faults/0.2.1-3/os_faults/cmd/cmd.py",
    "stat": {
        "perms": "rw-r--r--",
        "size": 5540,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "0.2.1-3"
}