{
    "checksum": "4465df52795c0c63916849c37263317fa087a4072f96b0a1b58844e0faf0fc83",
    "file": "pygraph.classes.exceptions.AlgorithmError-class.html",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/xml"
    },
    "number_of_duplicates": 1,
    "package": "python-graph",
    "path": "python-graph/1.8.2-6/docs/pygraph.classes.exceptions.AlgorithmError-class.html",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 850,
        "license": "/copyright/license/python-graph/1.8.2-6/",
        "metric": {
            "size": 1396
        },
        "pts_link": "https://tracker.debian.org/pkg/python-graph",
        "sloc": [
            [
                "python",
                3483
            ],
            [
                "makefile",
                92
            ]
        ],
        "suites": [
            "jessie",
            "jessie-kfreebsd",
            "stretch"
        ],
        "vcs_browser": "http://anonscm.debian.org/viewvc/python-modules/packages/python-graph/trunk/",
        "vcs_type": "svn"
    },
    "raw_url": "/data/main/p/python-graph/1.8.2-6/docs/pygraph.classes.exceptions.AlgorithmError-class.html",
    "stat": {
        "perms": "rw-r--r--",
        "size": 7034,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "1.8.2-6"
}