{
    "checksum": "c4d3f6c4e5f7c4af5ec38ff4d1e99dd6fcf47bb4dab53ed16ff8f8f24e4a6b68",
    "file": "bug-1674915-allow-user-access-fix-495b3e42bdc985ec.yaml",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/plain"
    },
    "number_of_duplicates": 6,
    "package": "python-manilaclient",
    "path": "python-manilaclient/3.0.0-3/releasenotes/notes/bug-1674915-allow-user-access-fix-495b3e42bdc985ec.yaml",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-manilaclient/3.0.0-3/",
        "metric": {
            "size": 2840
        },
        "pts_link": "https://tracker.debian.org/pkg/python-manilaclient",
        "sloc": [
            [
                "python",
                37219
            ],
            [
                "sh",
                151
            ],
            [
                "makefile",
                97
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/openstack-team/clients/python-manilaclient",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-manilaclient/3.0.0-3/releasenotes/notes/bug-1674915-allow-user-access-fix-495b3e42bdc985ec.yaml",
    "stat": {
        "perms": "rw-r--r--",
        "size": 163,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "3.0.0-3"
}